services:
  backend:
    build: ./backend
    container_name: backend
    env_file: [.env]
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    env_file: [.env]
    ports:
      - "5173:5173"
    restart: unless-stopped

  reverse-proxy:
    image: nginx:1.27-alpine
    container_name: reverse-proxy
    depends_on: [backend, frontend]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/nginx.https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  # certbot:
    # image: certbot/certbot:latest
    # container_name: certbot
    # depends_on: [reverse-proxy]
    # # we need docker.sock to reload nginx after renew
    # volumes:
      # - ./letsencrypt:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./certbot/renew.sh:/renew.sh:ro
    # environment:
      # DOMAINS: "www.serenespaceai.com serenespaceai.com"
      # EMAIL: "sujayoggu@gmail.com"
      # WEBROOT: "/var/www/certbot"
      # PROXY_NAME: "reverse-proxy"
      # HEALTH_URL_HTTP: "http://reverse-proxy/.well-known/acme-challenge/health"
      # # HEALTH_URL_HTTP: "http://www.serenespaceai.com/.well-known/acme-challenge/health"
      # # HEALTH_URL_ROOT: "http://www.serenespaceai.com/"
      # RUN_AT_MINUTE: "5"   # run daily at 00:05
    # entrypoint: ["/bin/sh","/renew.sh"]